baseURL = "http://RyunosukeFunasako.github.io/"
languageCode = "ja"
title = "RyuBlog"
theme = "hugo-theme-sam"

defaultContentLanguage   = "jp"
isMultilingual           = false
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "RyuBlog"

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "RyuBlog"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[[params.mainMenu]]
    link = "gallery"
    text = "gallery"



[[params.mainMenu]]
    link = "about"
    text = "who is Ryu?"

[imaging]
    quality = 75
